[package]
name = "sha512_half_test"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
rand = "0.8"
sha2 = "0.10.6"